[
  {
    "discussion_id": "2010508649",
    "pr_number": 88980,
    "pr_file": "tensorflow/python/client/device_lib.py",
    "created_at": "2025-03-24T16:18:37+00:00",
    "commented_code": "# pylint: disable=invalid-import-order, g-bad-import-order, wildcard-import, unused-import, undefined-variable\n from tensorflow.python import pywrap_tensorflow\n from tensorflow.python.client import _pywrap_device_lib\n+from tensorflow.python.platform import tf_logging as logging",
    "repo_full_name": "tensorflow/tensorflow",
    "discussion_comments": [
      {
        "comment_id": "2010508649",
        "repo_full_name": "tensorflow/tensorflow",
        "pr_number": 88980,
        "pr_file": "tensorflow/python/client/device_lib.py",
        "discussion_id": "2010508649",
        "commented_code": "@@ -18,6 +18,7 @@\n # pylint: disable=invalid-import-order, g-bad-import-order, wildcard-import, unused-import, undefined-variable\n from tensorflow.python import pywrap_tensorflow\n from tensorflow.python.client import _pywrap_device_lib\n+from tensorflow.python.platform import tf_logging as logging",
        "comment_created_at": "2025-03-24T16:18:37+00:00",
        "comment_author": "mihaimaruseac",
        "comment_body": "For this import, you also need to change the BUILD file to include the target there.\r\n\r\n```\r\nERROR: Strict deps violations: //tensorflow/python/client:device_lib\r\n  In tensorflow/python/client/device_lib.py, no direct deps found for imports:\r\n    line 21: from tensorflow.python.platform import tf_logging as logging: Module \"tensorflow.python.platform\" not provided by a direct dep\r\n```",
        "pr_file_module": null
      }
    ]
  },
  {
    "discussion_id": "1586698562",
    "pr_number": 44950,
    "pr_file": "tensorflow/python/tools/optimize_for_inference_test.py",
    "created_at": "2024-05-01T19:17:12+00:00",
    "commented_code": "from tensorflow.python.framework import test_util\n from tensorflow.python.ops import array_ops\n from tensorflow.python.ops import gen_nn_ops\n+from tensorflow.python.ops import gen_math_ops",
    "repo_full_name": "tensorflow/tensorflow",
    "discussion_comments": [
      {
        "comment_id": "1586698562",
        "repo_full_name": "tensorflow/tensorflow",
        "pr_number": 44950,
        "pr_file": "tensorflow/python/tools/optimize_for_inference_test.py",
        "discussion_id": "1586698562",
        "commented_code": "@@ -28,6 +28,7 @@\n from tensorflow.python.framework import test_util\n from tensorflow.python.ops import array_ops\n from tensorflow.python.ops import gen_nn_ops\n+from tensorflow.python.ops import gen_math_ops",
        "comment_created_at": "2024-05-01T19:17:12+00:00",
        "comment_author": "cantonios",
        "comment_body": "The test is failing because of a dependency error:\r\n```\r\nERROR: Strict deps violations: //tensorflow/python/tools:optimize_for_inference_test\r\n  In tensorflow/python/tools/optimize_for_inference_test.py, no direct deps found for imports:\r\n    line 31: from tensorflow.python.ops import gen_math_ops: Module \"tensorflow.python.ops\" not provided by a direct dep\r\n```",
        "pr_file_module": null
      },
      {
        "comment_id": "1586791022",
        "repo_full_name": "tensorflow/tensorflow",
        "pr_number": 44950,
        "pr_file": "tensorflow/python/tools/optimize_for_inference_test.py",
        "discussion_id": "1586698562",
        "commented_code": "@@ -28,6 +28,7 @@\n from tensorflow.python.framework import test_util\n from tensorflow.python.ops import array_ops\n from tensorflow.python.ops import gen_nn_ops\n+from tensorflow.python.ops import gen_math_ops",
        "comment_created_at": "2024-05-01T20:29:47+00:00",
        "comment_author": "yimeisun123",
        "comment_body": "I probably use a different build environment, this failure didn't happen to my local runs, all the test cases passed. Anyway, I added a dependency in the BUILD file and hopefully, this will fix the error. \r\nThanks again for helping with this old PR. ",
        "pr_file_module": null
      },
      {
        "comment_id": "1586793134",
        "repo_full_name": "tensorflow/tensorflow",
        "pr_number": 44950,
        "pr_file": "tensorflow/python/tools/optimize_for_inference_test.py",
        "discussion_id": "1586698562",
        "commented_code": "@@ -28,6 +28,7 @@\n from tensorflow.python.framework import test_util\n from tensorflow.python.ops import array_ops\n from tensorflow.python.ops import gen_nn_ops\n+from tensorflow.python.ops import gen_math_ops",
        "comment_created_at": "2024-05-01T20:31:52+00:00",
        "comment_author": "cantonios",
        "comment_body": "Our internal tooling is more strict about build dependencies.  Will run it again.",
        "pr_file_module": null
      }
    ]
  }
]